### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ravelll** [ravelll/rails_sandbox#3]
- [ ] Provide REST API
- [ ] Dockerize
- [ ] Provide GraphQL API
- [ ] Publish API document by Swagger UI

**Comment by ravelll** [comment]
test
